version: '3.8'

services:
  server:
    command: flask run --host=0.0.0.0
    build: 
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URI=${DATABASE_URI}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql


  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - server

volumes:
  postgres_data:
